<?php

/**
 * @file
 * Primary module hooks for movie_menu module.
 */

use Drupal\node\NodeInterface;

/**
 * Implements node view hook to alter movie budget message on node view.
 *
 * @param array &$build
 *   A render array having node content.
 * @param \Drupal\node\NodeInterface $node
 *   The node entity being viewed.
 * @param string $view_mode
 *   The view mode the particular node.
 * @param string $langcode
 *   The current language code.
 */
function movie_menu_node_view(array &$build, NodeInterface $node, $view_mode, $langcode) {
  if ($node->getType() == 'movie') {
    $config = \Drupal::config('movie_menu.settings');
    $budget_amount = $config->get('budget_friendly_amount');
    $movie_amount = $node->get('field_movie_price')->value;

    $budget_amount = (float) $budget_amount;
    $movie_amount = (float) $movie_amount;
    if ($budget_amount > $movie_amount) {
      $message = t("The movie is under budget.");
    }
    elseif ($budget_amount < $movie_amount) {
      $message = t("The movie is over budget.");
    }
    else {
      $message = t("The movie is within budget.");
    }

    $build['budget_message'] = [
      '#markup' => '<div>Movie budget:' . $message . '</div>',
      '#weight' => -10,
    ];
  }
}
