<?php
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 * 
 * Alters the user login form to add a custom submit handler that redirects
 * users to a welcome page after successful login.
 * 
 * @param array $form
 *   The full form array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The current state of the form.
 * @param string $form_id
 *   The unique ID of the form being altered.
 * 
 * @see welcome_block_login_redirect()
 */
function welcome_block_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#submit'][] = 'welcome_block_login_redirect';
}

/**
 * Custom submit handler for user login form. 
 * Redirects the user to custom welcome block page  after login.
 * 
 * @param array $form
 *   The full form array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The current state of the form.
 */
function welcome_block_login_redirect(array &$form, FormStateInterface $form_state) {
  $form_state->setRedirect('welcome_block.custom_welcome_block');
}
