<?php
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function welcome_block_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#submit'][] = 'welcome_block_login_redirect';
}

/**
 * Custom login redirect after user successfully logs in.
 */
function welcome_block_login_redirect(array &$form, FormStateInterface $form_state) {
  $form_state->setRedirect('welcome_block.custom_welcome_block');
}
?>
